# Generated by Django 5.1.7 on 2025-03-25 00:09

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=50)),
                ('med_number', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('service', models.CharField(max_length=255)),
                ('support_plan', models.TextField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('file', models.FileField(upload_to=reports.models.report_upload_to)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.provider')),
            ],
        ),
    ]
